FILES = env/driver.sv env/coverage.sv env/dut_out_a.sv env/dut_out_b.sv env/dut_out_c.sv env/dut_out_d.sv env/env.sv env/gen.sv env/IF.sv env/monitor.sv env/scoreboard.sv env/Transaction.sv hdl/adder.v hdl/adder_input_stage.v hdl/adder_output_stage.v hdl/adder_test.v hdl/calc3_top.v hdl/calc3_top.v.bak hdl/holdreg.v hdl/mux_out.v hdl/priority.v hdl/registers.v hdl/shifter.v hdl/shift_input_stage.v hdl/shift_output_stage.v hdl/testbench.v hdl/top.sv test/test.sv
TOPLEVEL = top

include Makefiles/non_DPI/Makefile_non_DPI