FILES = env/coverage.sv env/driver.sv env/dut_out_a.sv env/dut_out_b.sv env/dut_out_c.sv env/dut_out_d.sv env/env.sv env/gen.sv env/IF.sv env/monitor.sv env/scoreboard.sv env/Transaction.sv hdl/adder.v hdl/alu_input_stage.v hdl/alu_output_stage.v hdl/calc2_top.v hdl/holdreg.v hdl/mux_out.v hdl/priority.v hdl/shifter.v hdl/top.sv test/test.sv
TOPLEVEL = top

include Makefiles/non_DPI/Makefile_non_DPI