FILES = env/coverage.sv env/driver.sv env/dut_out_a.sv env/dut_out_b.sv env/dut_out_c.sv env/dut_out_d.sv env/env.sv env/gen.sv env/IF.sv env/monitor.sv env/scoreboard.sv hdl/calc1_top.v hdl/top.sv test/test.sv hdl/alu_input_stage.v hdl/alu_output_stage.v hdl/exdbin_mac.v hdl/exdbin_mac_test.v hdl/holdreg.v hdl/holdreg_test.v hdl/mux_out.v hdl/mux_test.v hdl/priority.v hdl/shifter.v
TOPLEVEL = top

include Makefiles/non_DPI/Makefile_non_DPI